name: Compila Gestionale Gitemania per Windows (Modalita Cartella Veloce)

on: [push]

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Installa le dipendenze
        env:
          PYTHONUTF8: "1"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: cmd

      - name: Compila l'eseguibile (modalita cartella)
        env:
          PYTHONUTF8: "1"
        run: |
          python setup.py build
        shell: cmd

      - name: Upload della cartella compilata
        uses: actions/upload-artifact@v4
        with:
          name: GestionaleGitemania-Windows-Cartella
          path: dist/GestionaleGitemania/ # <-- MODIFICA: Carica la cartella principale
